name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install frontend
      run: cd front && npm install .
    - name: build frontend
      run: cd front && npm run build
    - name: lint frontend
      run: cd front && npm run lint
